#!/bin/bash

[[ -z "$REDIS_CACHE" ]] && exit 0

otrs.Console.pl Admin::Config::Update --setting-name "Cache::Module" --value "Kernel::System::Cache::Redis" --no-deploy
otrs.Console.pl Admin::Config::Update --setting-name "Cache::Redis###Server" --value "$REDIS_CACHE" --no-deploy
